In [1]:
import pandas as pd

In [3]:
file = "Customer_Retention_Churn_Analysis_50K_Messy_Dataset.xlsx"

customers = pd.read_excel(file, sheet_name = "Customers")
customers

,CustomerID,Gender,Age,Country,AcquisitionChannel,SignupDate,Plan,MonthlyFee,TenureMonths,PaymentMethod,AutoRenew,LastLoginDaysAgo,AvgMonthlyUsageHours,SupportTickets,SatisfactionScore,Churn
0,C000001,NaN,23,NaN,Organic,2024-10-30,Premium,39.99,2,NaN,No,132,NaN,0,NaN,No
1,C000002,Male,58,USA,Ads,2021-10-20,Standard,19.99,23,UPI,No,145,45.8,6,3.0,No
2,C000003,Male,32,India,Referral,2024-04-13,Basic,9.99,7,Bank Transfer,Yes,62,80.2,6,7.0,No
3,C000004,Female,66,Australia,Organic,2022-11-01,Premium,39.99,9,Card,No,117,20.7,7,4.0,No
4,C000005,Other,48,Australia,Social,2021-06-03,Basic,9.99,25,Card,No,122,65.7,8,8.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50115,C001116,Female,30,USA,Organic,2024-05-18,Premium,39.99,41,Card,No,38,46.2,1,5.0,No
50116,C001117,Female,26,Australia,Partner,2021-04-26,Standard,19.99,27,Card,Yes,141,10.6,7,10.0,No
50117,C001118,Female,32,Canada,Social,2022-03-16,Premium,39.99,35,UPI,No,84,43.6,2,5.0,No
50118,C001119,Female,36,Canada,Ads,2024-08-25,Basic,9.99,33,PayPal,No,67,35.8,6,10.0,No
50119,C001120,Male,66,Australia,Ads,2024-04-23,Premium,39.99,49,UPI,No,107,8.5,6,7.0,No

In [4]:
# Droping Duplicates

customers = customers.drop_duplicates()
customers

,CustomerID,Gender,Age,Country,AcquisitionChannel,SignupDate,Plan,MonthlyFee,TenureMonths,PaymentMethod,AutoRenew,LastLoginDaysAgo,AvgMonthlyUsageHours,SupportTickets,SatisfactionScore,Churn
0,C000001,NaN,23,NaN,Organic,2024-10-30,Premium,39.99,2,NaN,No,132,NaN,0,NaN,No
1,C000002,Male,58,USA,Ads,2021-10-20,Standard,19.99,23,UPI,No,145,45.8,6,3.0,No
2,C000003,Male,32,India,Referral,2024-04-13,Basic,9.99,7,Bank Transfer,Yes,62,80.2,6,7.0,No
3,C000004,Female,66,Australia,Organic,2022-11-01,Premium,39.99,9,Card,No,117,20.7,7,4.0,No
4,C000005,Other,48,Australia,Social,2021-06-03,Basic,9.99,25,Card,No,122,65.7,8,8.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49996,C049997,Female,19,Canada,Ads,2023-12-23,Basic,9.99,25,PayPal,Yes,82,40.0,6,1.0,No
49997,C049998,Male,30,UK,Ads,2021-06-25,Standard,19.99,17,PayPal,Yes,118,65.6,4,10.0,No
49998,C049999,Other,30,India,Ads,2022-11-22,Basic,9.99,7,Card,Yes,121,11.2,6,4.0,No
49999,C050000,Male,55,India,Social,2025-02-09,Basic,9.99,22,UPI,Yes,29,14.3,5,10.0,No
50067,C001068,Other,48,Germany,Social,2021-03-28,Basic,9.99,50,UPI,Yes,141,23.8,2,8.0,No

In [5]:
# Cross verifying duplicates

customers.duplicated().sum()

np.int64(0)

In [6]:
customers.isnull().sum()

CustomerID                0
Gender                  516
Age                       0
Country                 516
AcquisitionChannel        0
SignupDate                0
Plan                      0
MonthlyFee                0
TenureMonths              0
PaymentMethod           516
AutoRenew                 0
LastLoginDaysAgo          0
AvgMonthlyUsageHours    516
SupportTickets            0
SatisfactionScore       516
Churn                     0
dtype: int64

In [8]:
# Handiling NULL values

customers['Gender'] = customers['Gender'].fillna(customers['Gender'].mode()[0])

customers['Country'] = customers['Country'].fillna(customers['Country'].mode()[0])

customers['PaymentMethod'] = customers['PaymentMethod'].fillna(customers['PaymentMethod'].mode()[0])

customers['AvgMonthlyUsageHours'] = customers['AvgMonthlyUsageHours'].fillna(customers['AvgMonthlyUsageHours'].median())

customers['SatisfactionScore'] = customers['SatisfactionScore'].fillna(customers['SatisfactionScore'].median())

customers

C:\Users\deeli\AppData\Local\Temp\ipykernel_45928\4127050280.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['Gender'] = customers['Gender'].fillna(customers['Gender'].mode()[0])
C:\Users\deeli\AppData\Local\Temp\ipykernel_45928\4127050280.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['Country'] = customers['Country'].fillna(customers['Country'].mode()[0])
C:\Users\deeli\AppData\Local\Temp\ipykernel_45928\4127050280.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['PaymentMethod'] = customers['PaymentMethod'].fillna(customers['PaymentMethod'].mode()[0])
C:\Users\deeli\AppData\Local\Temp\ipykernel_45928\4127050280.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['AvgMonthlyUsageHours'] = customers['AvgMonthlyUsageHours'].fillna(customers['AvgMonthlyUsageHours'].median())
C:\Users\deeli\AppData\Local\Temp\ipykernel_45928\4127050280.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['SatisfactionScore'] = customers['SatisfactionScore'].fillna(customers['SatisfactionScore'].median())

,CustomerID,Gender,Age,Country,AcquisitionChannel,SignupDate,Plan,MonthlyFee,TenureMonths,PaymentMethod,AutoRenew,LastLoginDaysAgo,AvgMonthlyUsageHours,SupportTickets,SatisfactionScore,Churn
0,C000001,Male,23,Canada,Organic,2024-10-30,Premium,39.99,2,Card,No,132,40.4,0,5.0,No
1,C000002,Male,58,USA,Ads,2021-10-20,Standard,19.99,23,UPI,No,145,45.8,6,3.0,No
2,C000003,Male,32,India,Referral,2024-04-13,Basic,9.99,7,Bank Transfer,Yes,62,80.2,6,7.0,No
3,C000004,Female,66,Australia,Organic,2022-11-01,Premium,39.99,9,Card,No,117,20.7,7,4.0,No
4,C000005,Other,48,Australia,Social,2021-06-03,Basic,9.99,25,Card,No,122,65.7,8,8.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49996,C049997,Female,19,Canada,Ads,2023-12-23,Basic,9.99,25,PayPal,Yes,82,40.0,6,1.0,No
49997,C049998,Male,30,UK,Ads,2021-06-25,Standard,19.99,17,PayPal,Yes,118,65.6,4,10.0,No
49998,C049999,Other,30,India,Ads,2022-11-22,Basic,9.99,7,Card,Yes,121,11.2,6,4.0,No
49999,C050000,Male,55,India,Social,2025-02-09,Basic,9.99,22,UPI,Yes,29,14.3,5,10.0,No
50067,C001068,Other,48,Germany,Social,2021-03-28,Basic,9.99,50,UPI,Yes,141,23.8,2,8.0,No

In [9]:
customers['SignupDate'] = pd.to_datetime(customers['SignupDate'])
customers

C:\Users\deeli\AppData\Local\Temp\ipykernel_45928\949829746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['SignupDate'] = pd.to_datetime(customers['SignupDate'])

,CustomerID,Gender,Age,Country,AcquisitionChannel,SignupDate,Plan,MonthlyFee,TenureMonths,PaymentMethod,AutoRenew,LastLoginDaysAgo,AvgMonthlyUsageHours,SupportTickets,SatisfactionScore,Churn
0,C000001,Male,23,Canada,Organic,2024-10-30,Premium,39.99,2,Card,No,132,40.4,0,5.0,No
1,C000002,Male,58,USA,Ads,2021-10-20,Standard,19.99,23,UPI,No,145,45.8,6,3.0,No
2,C000003,Male,32,India,Referral,2024-04-13,Basic,9.99,7,Bank Transfer,Yes,62,80.2,6,7.0,No
3,C000004,Female,66,Australia,Organic,2022-11-01,Premium,39.99,9,Card,No,117,20.7,7,4.0,No
4,C000005,Other,48,Australia,Social,2021-06-03,Basic,9.99,25,Card,No,122,65.7,8,8.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49996,C049997,Female,19,Canada,Ads,2023-12-23,Basic,9.99,25,PayPal,Yes,82,40.0,6,1.0,No
49997,C049998,Male,30,UK,Ads,2021-06-25,Standard,19.99,17,PayPal,Yes,118,65.6,4,10.0,No
49998,C049999,Other,30,India,Ads,2022-11-22,Basic,9.99,7,Card,Yes,121,11.2,6,4.0,No
49999,C050000,Male,55,India,Social,2025-02-09,Basic,9.99,22,UPI,Yes,29,14.3,5,10.0,No
50067,C001068,Other,48,Germany,Social,2021-03-28,Basic,9.99,50,UPI,Yes,141,23.8,2,8.0,No

In [10]:
subscriptions = pd.read_excel(file, sheet_name = "Subscriptions")
subscriptions

,SubscriptionID,CustomerID,StartDate,RenewalDate,ContractType,DiscountPct,Status
0,S000001,C000001,2025-09-13,2026-04-11,Monthly,NaN,Cancelled
1,S000002,C000002,2021-12-13,2022-02-11,Annual,20.0,Active
2,S000003,C000003,2023-04-28,2024-04-22,Monthly,20.0,Expired
3,S000004,C000004,2023-09-10,2024-04-07,Annual,15.0,Expired
4,S000005,C000005,2024-06-23,2025-02-18,Monthly,15.0,Expired
...,...,...,...,...,...,...,...
49995,S049996,C049996,2021-09-19,2022-04-17,Monthly,0.0,Cancelled
49996,S049997,C049997,2024-11-12,2025-01-11,Monthly,0.0,Active
49997,S049998,C049998,2022-11-23,2023-06-21,Annual,20.0,Expired
49998,S049999,C049999,2023-02-01,2023-09-29,Annual,10.0,Expired
49999,S050000,C050000,2025-09-06,2026-01-04,Monthly,5.0,Active

In [11]:
subscriptions.duplicated().sum()

np.int64(0)

In [12]:
subscriptions.isnull().sum()

SubscriptionID      0
CustomerID          0
StartDate           0
RenewalDate         0
ContractType        0
DiscountPct       237
Status              0
dtype: int64

In [13]:
# Handiling NULL Values

subscriptions['DiscountPct'] = subscriptions['DiscountPct'].fillna(subscriptions['DiscountPct'].median())
subscriptions

,SubscriptionID,CustomerID,StartDate,RenewalDate,ContractType,DiscountPct,Status
0,S000001,C000001,2025-09-13,2026-04-11,Monthly,10.0,Cancelled
1,S000002,C000002,2021-12-13,2022-02-11,Annual,20.0,Active
2,S000003,C000003,2023-04-28,2024-04-22,Monthly,20.0,Expired
3,S000004,C000004,2023-09-10,2024-04-07,Annual,15.0,Expired
4,S000005,C000005,2024-06-23,2025-02-18,Monthly,15.0,Expired
...,...,...,...,...,...,...,...
49995,S049996,C049996,2021-09-19,2022-04-17,Monthly,0.0,Cancelled
49996,S049997,C049997,2024-11-12,2025-01-11,Monthly,0.0,Active
49997,S049998,C049998,2022-11-23,2023-06-21,Annual,20.0,Expired
49998,S049999,C049999,2023-02-01,2023-09-29,Annual,10.0,Expired
49999,S050000,C050000,2025-09-06,2026-01-04,Monthly,5.0,Active

In [14]:
subscriptions.isnull().sum()

SubscriptionID    0
CustomerID        0
StartDate         0
RenewalDate       0
ContractType      0
DiscountPct       0
Status            0
dtype: int64

In [15]:
subscriptions['StartDate'] = pd.to_datetime(subscriptions['StartDate'])
subscriptions['RenewalDate'] = pd.to_datetime(subscriptions['RenewalDate'])
subscriptions

,SubscriptionID,CustomerID,StartDate,RenewalDate,ContractType,DiscountPct,Status
0,S000001,C000001,2025-09-13,2026-04-11,Monthly,10.0,Cancelled
1,S000002,C000002,2021-12-13,2022-02-11,Annual,20.0,Active
2,S000003,C000003,2023-04-28,2024-04-22,Monthly,20.0,Expired
3,S000004,C000004,2023-09-10,2024-04-07,Annual,15.0,Expired
4,S000005,C000005,2024-06-23,2025-02-18,Monthly,15.0,Expired
...,...,...,...,...,...,...,...
49995,S049996,C049996,2021-09-19,2022-04-17,Monthly,0.0,Cancelled
49996,S049997,C049997,2024-11-12,2025-01-11,Monthly,0.0,Active
49997,S049998,C049998,2022-11-23,2023-06-21,Annual,20.0,Expired
49998,S049999,C049999,2023-02-01,2023-09-29,Annual,10.0,Expired
49999,S050000,C050000,2025-09-06,2026-01-04,Monthly,5.0,Active

In [16]:
supportTickets = pd.read_excel(file, sheet_name = "SupportTickets")
supportTickets

      TicketID CustomerID     IssueType Priority  ResolutionDays Resolved
0      T000001    C041540           NaN      Low               6      Yes
1      T000002    C022332         Login   Medium               6      Yes
2      T000003    C040310           Bug      Low               7      Yes
3      T000004    C041745           Bug      Low              14       No
4      T000005    C048359       Billing      Low               5      Yes
...        ...        ...           ...      ...             ...      ...
19995  T019996    C012554  Cancellation      Low               6       No
19996  T019997    C002997         Login   Medium               1       No
19997  T019998    C000114           Bug      Low               9       No
19998  T019999    C038046         Login   Medium              10      Yes
19999  T020000    C046274       Feature   Medium               8      Yes

[20000 rows x 6 columns]

In [17]:
supportTickets.duplicated().sum()

np.int64(0)

In [18]:
supportTickets.isnull().sum()

TicketID            0
CustomerID          0
IssueType         128
Priority            0
ResolutionDays      0
Resolved            0
dtype: int64

In [19]:
# Handiling NULL values

supportTickets['IssueType'] = supportTickets['IssueType'].fillna(supportTickets['IssueType'].mode()[0])
supportTickets

      TicketID CustomerID     IssueType Priority  ResolutionDays Resolved
0      T000001    C041540           Bug      Low               6      Yes
1      T000002    C022332         Login   Medium               6      Yes
2      T000003    C040310           Bug      Low               7      Yes
3      T000004    C041745           Bug      Low              14       No
4      T000005    C048359       Billing      Low               5      Yes
...        ...        ...           ...      ...             ...      ...
19995  T019996    C012554  Cancellation      Low               6       No
19996  T019997    C002997         Login   Medium               1       No
19997  T019998    C000114           Bug      Low               9       No
19998  T019999    C038046         Login   Medium              10      Yes
19999  T020000    C046274       Feature   Medium               8      Yes

[20000 rows x 6 columns]

In [20]:
supportTickets.isnull().sum()

TicketID          0
CustomerID        0
IssueType         0
Priority          0
ResolutionDays    0
Resolved          0
dtype: int64

In [21]:
# Saving all the 3 files into CSV

customers.to_csv('customers_cleaned.csv', index = False)
subscriptions.to_csv('subscriptions_cleaned.csv', index = False)
supportTickets.to_csv('SupportTickets_cleaned.csv', index = False)